DROP USER sakila CASCADE;
CREATE USER sakila IDENTIFIED BY sakila
	DEFAULT TABLESPACE USERS
	TEMPORARY TABLESPACE temp;
GRANT UNLIMITED TABLESPACE TO sakila;
ALTER USER sakila ACCOUNT UNLOCK;
GRANT CREATE SESSION TO sakila;
GRANT CREATE TABLE TO sakila;
GRANT CREATE VIEW To sakila;
GRANT CREATE PROCEDURE TO sakila;
GRANT CREATE TRIGGER TO sakila;
GRANT CREATE SEQUENCE TO sakila;

exit;